// Generated by scripts/generate-design-tokens.mjs.
using Avalonia.Controls;
using Avalonia.Media;
using Avalonia.Styling;
using Colibri.Core.Settings;

namespace Colibri.App.Resources;

internal static class DesignPalettes
{
    internal sealed record SurfaceColors(string Chrome, string Pane, string Card, string Divider, string Mica, string ChromeMica);
    internal static (SurfaceColors Light, SurfaceColors Dark) Get(string id) => BackgroundPalettes.Normalize(id) switch
    {
            "warm" => (new SurfaceColors("#F3F3F3", "#FFFFFF", "#FFFFFF", "#14000000", "#B3FFFFFF", "#00000000"), new SurfaceColors("#202020", "#272727", "#2B2B2B", "#19FFFFFF", "#4D3A3A3A", "#00000000")),
            "graphite" => (new SurfaceColors("#ECEEF1", "#F8F9FB", "#FFFFFF", "#14000000", "#B3F8F9FB", "#50ECEEF1"), new SurfaceColors("#1C1F24", "#252A31", "#2D333C", "#19FFFFFF", "#4D2D333C", "#701C1F24")),
            "ocean" => (new SurfaceColors("#E8F0F5", "#F5FAFD", "#FFFFFF", "#14000000", "#B3F5FAFD", "#50E8F0F5"), new SurfaceColors("#17232E", "#20313F", "#293C4B", "#19FFFFFF", "#4D293C4B", "#7017232E")),
            "forest" => (new SurfaceColors("#EAF0EA", "#F6FAF6", "#FFFFFF", "#14000000", "#B3F6FAF6", "#50EAF0EA"), new SurfaceColors("#1B271F", "#26352B", "#304235", "#19FFFFFF", "#4D304235", "#701B271F")),
            _ => throw new System.InvalidOperationException()
    };

    internal static ResourceDictionary Create(string id)
    {
        var colors = Get(id);
        var dictionary = new ResourceDictionary();
        dictionary.ThemeDictionaries[ThemeVariant.Light] = CreateVariant(colors.Light);
        dictionary.ThemeDictionaries[ThemeVariant.Dark] = CreateVariant(colors.Dark);
        return dictionary;
    }

    private static ResourceDictionary CreateVariant(SurfaceColors colors) => new()
    {
        ["ChromeBackgroundBrush"] = new SolidColorBrush(Color.Parse(colors.Chrome)),
        ["ContentPaneBrush"] = new SolidColorBrush(Color.Parse(colors.Pane)),
        ["CardBrush"] = new SolidColorBrush(Color.Parse(colors.Card)),
        ["DividerBrush"] = new SolidColorBrush(Color.Parse(colors.Divider)),
        ["ContentPaneMicaBrush"] = new SolidColorBrush(Color.Parse(colors.Mica)),
        ["ChromeMicaBrush"] = new SolidColorBrush(Color.Parse(colors.ChromeMica))
    };
}
