// Generated by scripts/generate-capture-policy.mjs. Edit docs/capture-policy.json.
using Colibri.Core.Models;

namespace Colibri.Core.Services;

public static class CaptureCatalog
{
    public static class Reasons
    {
        public const string Disabled = "disabled";
        public const string Private = "private";
        public const string Excluded = "excluded";
        public const string Method = "method";
        public const string Minimum = "minimum";
        public const string Preference = "preference";
        public const string Scheme = "scheme";
        public const string Rules = "rules";
        public const string Incognito = "incognito";
        public const string Safety = "safety";
    }
    public sealed record CategoryDefinition(string Id, DownloadCategory Category, IReadOnlyList<string> Extensions);
    public static IReadOnlyList<CategoryDefinition> Categories { get; } = Array.AsReadOnly<CategoryDefinition>([
        new("compressed", DownloadCategory.Compressed, Array.AsReadOnly<string>(["zip", "rar", "7z", "gz", "bz2", "xz", "tar", "tgz", "tbz2", "txz", "zst", "lz", "lzma", "cab", "iso"])),
        new("documents", DownloadCategory.Documents, Array.AsReadOnly<string>(["pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "odt", "ods", "odp", "txt", "rtf", "epub", "mobi", "csv", "md"])),
        new("music", DownloadCategory.Music, Array.AsReadOnly<string>(["mp3", "flac", "wav", "aac", "ogg", "oga", "m4a", "opus", "wma", "aiff", "alac", "mid", "midi"])),
        new("programs", DownloadCategory.Programs, Array.AsReadOnly<string>(["exe", "msi", "msix", "msixbundle", "appx", "dmg", "pkg", "deb", "rpm", "appimage", "apk", "flatpak", "snap", "run"])),
        new("video", DownloadCategory.Video, Array.AsReadOnly<string>(["mp4", "mkv", "avi", "mov", "webm", "wmv", "flv", "m4v", "mpg", "mpeg", "ts", "3gp", "ogv", "vob"])),
        new("other", DownloadCategory.Other, Array.AsReadOnly<string>([])),
    ]);
    public static IReadOnlyList<string> LegacyCaptureExtensions { get; } = Array.AsReadOnly<string>(["zip", "rar", "7z", "gz", "tar", "exe", "msi", "dmg", "pkg", "deb", "rpm", "appimage", "iso", "pdf", "epub", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "mp3", "flac", "wav", "mp4", "mkv", "avi", "mov", "webm"]);
}
